US12891: create installation script

diff --git a/resource/customize/OpenAM/script/OpenAM_customize_deploy_script.sh.template b/resource/customize/OpenAM/script/OpenAM_customize_deploy_script.sh.template
--- a/resource/customize/OpenAM/script/OpenAM_customize_deploy_script.sh.template
+++ b/resource/customize/OpenAM/script/OpenAM_customize_deploy_script.sh.template
@@ -2,7 +2,7 @@
 
 OPENAM_DIR=/usr/share/tomcat6/webapps/openam
 DISTINGUISHED_NAME="opensso"
-OFFSET=49
+OFFSET=64
 
 read -p "Enter OpenAM deployment directory [${OPENAM_DIR}]: " input
 OPENAM_DIR=${input:-${OPENAM_DIR}}
@@ -16,14 +16,27 @@ fi
 read -p "Enter distinguished name [${DISTINGUISHED_NAME}]: " input
 DISTINGUISHED_NAME=${input:-${DISTINGUISHED_NAME}}
 echo "Installing custom packages..."
-TMP_FILE=/tmp/customized_openam_login.$$.tar.gz
-tail -n+${OFFSET} $0 > ${TMP_FILE}
+TMP_FILE=/tmp/customized_openam_login.$$.cpio
+tail -n+${OFFSET} $0 > ${TMP_FILE}.gz
 RETVAL=$?
 if [ ${RETVAL} != 0 ]; then
     echo "Failed to generate file[${TMP_FILE}]"
     exit 1
 fi
+gunzip ${TMP_FILE}.gz
+RETVAL=$?
+if [ ${RETVAL} != 0 ]; then
+    echo "Failed to gunzip file[${TMP_FILE}]"
+    exit 1
+fi
+
 INSTALL_DIR=${OPENAM_DIR}/config/auth/${DISTINGUISHED_NAME}
+rm -rf ${INSTALL_DIR}
+RETVAL=$?
+if [ ${RETVAL} != 0 ]; then
+    echo "Failed to delete directory [${INSTALL_DIR}]"
+    exit 1
+fi
 if [ ! -d ${INSTALL_DIR} ]; then
     mkdir -p ${INSTALL_DIR}
     RETVAL=$?
@@ -38,11 +51,13 @@ if [ ! -w ${INSTALL_DIR} ]; then
     echo "Please check directory access"
     exit 1
 fi
-tar -C ${INSTALL_DIR} -zxf ${TMP_FILE}
+cd ${INSTALL_DIR}
+cpio -ivd < ${TMP_FILE}
 RETVAL=$?
 if [ ${RETVAL} != 0 ]; then
-    echo "Failed to install custom package at [${INSTALL_DIR}"
+    echo "Failed to install custom package at [${INSTALL_DIR}]"
     exit 1
 fi
 echo "Please restart tomcat"
-##### END OF SCRIPT ######
+rm -f ${TMP_FILE}
+exit 0
